version: "3.9"

services:
  spring-boot:
    build: .
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_management_system_db
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    networks:
      - my_network
  db:
    container_name: p_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: task_management_system_db
    ports:
      - "5432:5432"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge