app:
  jwt_secret: task-management-system-secret

spring:
  application:
    name: task-management-system
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/task_management_system_db
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true