--liquibase formatted sql

--changeset alex:1

CREATE TABLE task
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    title varchar NOT NULL,
    description text,
    status int,
    priority int,
    author int REFERENCES users(id),
    executor int references users(id)
)