--liquibase formatted sql

--changeset alex:1

CREATE TABLE comment
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id int REFERENCES users(id) NOT NULL,
    task_id int REFERENCES task(id),
    text text
)