--liquibase formatted sql

--changeset alex:1

CREATE TABLE users
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    email varchar NOT NULL UNIQUE ,
    password text NOT NULL,
    name varchar NOT NULL
)